apiVersion: v1
kind: Pod
metadata:
  name: cm-test-app
spec:
  containers:
  - name: kubeguide/tomcat-app:v1
    ports: 
    - containerPort: 8080
    volumeMounts:
    - name: serverxml
      mountPath: /configfile
  volumes:
  - name: serverxml
    configMap:
      name: cm-appconfiggfiles
      items:
      - key: key-serverxml
        path: server.xml
      - key: key-loggingproperties
        path: logging.properties